version: '3.7'

services:
  zookeeper-server:
    container_name: 'zookeeper-server'
    image: bitnami/zookeeper:latest
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
        - 2181:2181
    networks:
        - network1

  kafka-server:
    container_name: 'kafka-server'
    image: bitnami/kafka:latest
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-server:2181
    ports:
      - "9092:9092"
    networks:
        - network1

networks:
  network1: 
    name: 'kafka-network'
